services:
  app:
    ports: []
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK:?TRAEFIK_NETWORK is required}
      - traefik.http.routers.kuroi.rule=Host(`${TRAEFIK_DOMAIN:?TRAEFIK_DOMAIN is required}`)
      - traefik.http.routers.kuroi.entrypoints=${TRAEFIK_ENTRYPOINT:-websecure}
      - traefik.http.routers.kuroi.tls=${TRAEFIK_TLS:-true}
      - traefik.http.services.kuroi.loadbalancer.server.port=8000

networks:
  traefik:
    name: ${TRAEFIK_NETWORK:?TRAEFIK_NETWORK is required}
    external: true
